backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "englishPerks"
    label: "en/Perk"
    folder: "src/entities/en/perks"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Perk name", name: "title", widget: "string"}
      - {label: "Text", name: "text", widget: "string"}

  - name: "norwegianPerks"
    label: "no/Perk"
    folder: "src/entities/no/perks"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Perk name", name: "title", widget: "string"}
      - {label: "Text", name: "text", widget: "string"}

  - name: "norwegian_employees"
    label: "no/Employee"
    folder: "src/entities/no/employees"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Job title", name: "jobTitle", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - label: "Job type"
        name: "jobType"
        widget: "select"
        options:
        - {label: "Front-end", value: "frontEnd"}
        - {label: "Designer", value: "designer"}
        - {label: "Back-end", value: "backEnd"}
        - {label: "Management", value: "management"}
        - {label: "Operations", value: "operations"}
        - {label: "Support", value: "support"}
        - {label: "Summer intern", value: "summerIntern"}

  - name: "english_employees"
    label: "en/Employee"
    folder: "src/entities/en/employees"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Job title", name: "jobTitle", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - label: "Job type"
        name: "jobType"
        widget: "select"
        options:
        - {label: "Front-end", value: "frontEnd"}
        - {label: "Back-end", value: "backEnd"}
        - {label: "Management", value: "management"}
        - {label: "Operations", value: "operations"}
        - {label: "Summer intern", value: "summerIntern"}

  - name: "norwegian_featureCard"
    label: "no/FeatureCard"
    folder: "src/entities/no/featureCards"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Språk", name: "language", widget: "hidden", default: "no"}
      - {label: "Bilde", name: "image", widget: "image"}
      - {label: "Tittel", name: "title", widget: "string"}
      - {label: "Beskrivelse", name: "description", widget: "text"}
      - {label: "Features", name: "features", widget: "list"}

  - name: "english_featureCard"
    label: "en/FeatureCard"
    folder: "src/entities/en/featureCards"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Language", name: "language", widget: "hidden", default: "en"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Features", name: "features", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/no/index.md"
        name: "norwegian_index_page"
        label: "no/Homepage"
        fields:
          - label: "On top of animation"
            name: "onTopOfAnimation"
            widget: "object"
            fields:
              - {label: "Header", name: "title", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "string"}
          - label: "Transitional element"
            name: "transitionalElement"
            widget: "object"
            fields:
              - {label: "Numbers and text", name: "numbersAndText", widget: "object", fields: [
                  {label: "Companies number", name: "companiesNumber", widget: "string"}
                  {label: "Companies text", name: "companiesText", widget: "string"}
                  {label: "Users number", name: "usersNumber", widget: "string"}
                  {label: "Users text", name: "usersText", widget: "string"}
                  {label: "Text", name: "text", widget: "string"}
                ]}
              - label: "Customer logos" 
                name: "customerLogos"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Logo", name: "logo", widget: "image"}
          - label: "Investor portal"
            name: "investorPortal"
            widget: "object"
            fields:
              - {label: "Header", name: "header", widget: "string"}
              - {label: "Featured Image", name: "image", widget: "image"}
              - {label: "Text", name: "text", widget: "text"}
          - label: "Customization"
            name: "customization"
            widget: "object"
            fields:
              - {label: "Header", name: "header", widget: "string"}
              - {label: "Text", name: "text", widget: "text"}
              - {label: "Cards", name: "cards", widget: "list", fields: [
                  {label: "Header", name: "header", widget: "string"},
                  {label: "Image", name: "image", widget: "image"},
                  {label: "Description", name: "description", widget: "text"},
                  {label: "Features", name: "features", widget: "list"},
                  {label: "Dark", name: "isDark", widget: "boolean"},
                ]}
              - {label: "Service integrations", name: "serviceIntegrations", widget: "object", fields: [
                  {label: "Header", name: "header", widget: "string"},
                  {label: "Text", name: "text", widget: "text"},
                  {label: "Integration logos", name: "integrationLogos", widget: "list", fields: [
                    {label: "Name", name: "name", widget: "string"}
                    {label: "Logo", name: "logo", widget: "image"}
                  ]}
              ]}
          - label: "Other products"
            name: "otherProducts"
            widget: "object"
            fields:
              - {label: "Arena", name: "arena", widget: "object", fields: [
                  {label: "Image", name: "image", widget: "image"},
                  {label: "Header", name: "header", widget: "string"},
                  {label: "Text", name: "text", widget: "text"},
                ]}
              - {label: "IR Modules", name: "irModules", widget: "object", fields: [
                  {label: "Image", name: "image", widget: "image"},
                  {label: "Header", name: "header", widget: "string"},
                  {label: "Text", name: "text", widget: "text"},
                ]}

      - file: "src/pages/en/index.md"
        name: "english_index_page"
        label: "en/Homepage"
        fields:
          - label: "On top of animation"
            name: "onTopOfAnimation"
            widget: "object"
            fields:
              - {label: "Header", name: "title", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "string"}
          - label: "Transitional element"
            name: "transitionalElement"
            widget: "object"
            fields:
              - {label: "Numbers and text", name: "numbersAndText", widget: "object", fields: [
                  {label: "Companies number", name: "companiesNumber", widget: "string"}
                  {label: "Companies text", name: "companiesText", widget: "string"}
                  {label: "Users number", name: "usersNumber", widget: "string"}
                  {label: "Users text", name: "usersText", widget: "string"}
                  {label: "Text", name: "text", widget: "string"}
                ]}
              - label: "Customer logos" 
                name: "customerLogos"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Logo", name: "logo", widget: "image"}
          - label: "Investor portal"
            name: "investorPortal"
            widget: "object"
            fields:
              - {label: "Header", name: "header", widget: "string"}
              - {label: "Featured Image", name: "image", widget: "image"}
              - {label: "Text", name: "text", widget: "text"}
          - label: "Customization"
            name: "customization"
            widget: "object"
            fields:
              - {label: "Header", name: "header", widget: "string"}
              - {label: "Text", name: "text", widget: "text"}
              - {label: "Cards", name: "cards", widget: "list", fields: [
                  {label: "Header", name: "header", widget: "string"},
                  {label: "Image", name: "image", widget: "image"},
                  {label: "Description", name: "description", widget: "text"},
                  {label: "Features", name: "features", widget: "list"},
                  {label: "Dark", name: "isDark", widget: "boolean"},
                ]}
              - {label: "Service integrations", name: "serviceIntegrations", widget: "object", fields: [
                  {label: "Header", name: "header", widget: "string"},
                  {label: "Text", name: "text", widget: "text"},
                  {label: "Integration logos", name: "integrationLogos", widget: "list", fields: [
                    {label: "Name", name: "name", widget: "string"}
                    {label: "Logo", name: "logo", widget: "image"}
                  ]}
              ]}
          - label: "Other products"
            name: "otherProducts"
            widget: "object"
            fields:
              - {label: "Arena", name: "arena", widget: "object", fields: [
                  {label: "Image", name: "image", widget: "image"},
                  {label: "Header", name: "header", widget: "string"},
                  {label: "Text", name: "text", widget: "text"},
                ]}
              - {label: "IR Modules", name: "irModules", widget: "object", fields: [
                  {label: "Image", name: "image", widget: "image"},
                  {label: "Header", name: "header", widget: "string"},
                  {label: "Text", name: "text", widget: "text"},
                ]}

      - file: "src/pages/no/about/index.md"
        name: "norwegian_about_page"
        label: "no/About page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "aboutPage"}
          - {label: "First header", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Image Description", name: "imageAlt", widget: "string"}
          - {label: "Text", name: "text", widget: "text"}
          - {label: "Second header", name: "header", widget: "string"}

      - file: "src/pages/en/about/index.md"
        name: "english_about_page"
        label: "en/About page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "aboutPage"}
          - {label: "First header", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Image Description", name: "imageAlt", widget: "string"}
          - {label: "Text", name: "text", widget: "text"}
          - {label: "Second header", name: "header", widget: "string"}

      - file: "src/pages/no/career/index.md"
        name: "norwegian_career_page"
        label: "no/Career page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "careerPage"}
          - {label: "First header", name: "title", widget: "string"}
          - {label: "First image", name: "image1", widget: "image"}
          - {label: "First image description", name: "image1Alt", widget: "string"}
          - {label: "First text", name: "text1", widget: "text"}
          - {label: "Second header", name: "header", widget: "string"}
          - {label: "Second image", name: "image2", widget: "image"}
          - {label: "Second image description", name: "image2Alt", widget: "string"}
          - {label: "Second text", name: "text2", widget: "text"}
          - {label: "First sub-header", name: "subHeader1", widget: "string"}
          - {label: "Second sub-header", name: "subHeader2", widget: "string"}

      - file: "src/pages/en/career/index.md"
        name: "english_career_page"
        label: "en/Career page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "careerPage"}
          - {label: "First header", name: "title", widget: "string"}
          - {label: "First image", name: "image1", widget: "image"}
          - {label: "First Image Description", name: "image1Alt", widget: "string"}
          - {label: "First text", name: "text1", widget: "text"}
          - {label: "Second header", name: "header", widget: "string"}
          - {label: "Second image", name: "image2", widget: "image"}
          - {label: "Second image description", name: "image2Alt", widget: "string"}
          - {label: "Second text", name: "text2", widget: "text"}
          - {label: "First sub-header", name: "subHeader1", widget: "string"}
          - {label: "Second sub-header", name: "subHeader2", widget: "string"}

      - file: "src/pages/no/products/index.md"
        name: "norwegian_products_page"
        label: "no/Products page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "productsPage"}
          - {label: "Intro", name: "intro", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
            ]}
          - {label: "Investor Portals", name: "investorPortal", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Description", name: "description", widget: "text"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Features", name: "features", widget: "list", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Description", name: "description", widget: "text"},
                {label: "Image", name: "image", widget: "image"},
              ]},
            ]}
          - {label: "Products", name: "products", widget: "list", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Description", name: "description", widget: "text"},
            ]}


      - file: "src/pages/en/products/index.md"
        name: "english_products_page"
        label: "en/Products page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "productsPage"}
          - {label: "Intro", name: "intro", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
            ]}
          - {label: "Investor Portals", name: "investorPortal", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Description", name: "description", widget: "text"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Features", name: "features", widget: "list", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Description", name: "description", widget: "text"},
                {label: "Image", name: "image", widget: "image"},
              ]},
            ]}
          - {label: "Products", name: "products", widget: "list", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Description", name: "description", widget: "text"},
            ]}

      - file: "src/pages/no/responsibleDisclosure/index.md"
        name: "norwegian_responsibleDisclosure_page"
        label: "no/Responsible disclosure page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "responsibleDisclosurePage"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Contact info", name: "contactInfo", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Visiting address", name: "visitingAddress", widget: "string"},
              {label: "Phone number", name: "phoneNumber", widget: "string"},
              {label: "Mail address", name: "mailAddress", widget: "string"},
            ]}

      - file: "src/pages/en/responsibleDisclosure/index.md"
        name: "english_responsibleDisclosure_page"
        label: "en/Responsible disclosure page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "responsibleDisclosurePage"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Contact info", name: "contactInfo", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Visiting address", name: "visitingAddress", widget: "string"},
              {label: "Phone number", name: "phoneNumber", widget: "string"},
              {label: "Mail address", name: "mailAddress", widget: "string"},
            ]}

      - file: "src/pages/footer/index.md"
        name: "footer"
        label: "Footer"
        fields:
          - {label: "Group websites", name: "groupWebsites", widget: "object", fields: [
              {label: "Website", name: "website1", widget: "object", fields: [
                {label: "Website name", name: "title", widget: "string"},
                {label: "Url", name: "url", widget: "string"},
              ]},
              {label: "Website", name: "website2", widget: "object", fields: [
                {label: "Website name", name: "title", widget: "string"},
                {label: "Url", name: "url", widget: "string"},
              ]},
              {label: "Website", name: "website3", widget: "object", fields: [
                {label: "Website name", name: "title", widget: "string"},
                {label: "Url", name: "url", widget: "string"},
              ]},
              {label: "Website", name: "website4", widget: "object", fields: [
                {label: "Website name", name: "title", widget: "string"},
                {label: "Url", name: "url", widget: "string"},
              ]},
              {label: "Website", name: "website5", widget: "object", fields: [
                {label: "Website name", name: "title", widget: "string"},
                {label: "Url", name: "url", widget: "string"},
              ]},
              {label: "Website", name: "website6", widget: "object", fields: [
                {label: "Website name", name: "title", widget: "string"},
                {label: "Url", name: "url", widget: "string"},
              ]},
            ]}
          - {label: "Contact info", name: "contactInfo", widget: "object", fields: [
              {label: "Name", name: "title", widget: "string"},
              {label: "Visiting address", name: "visitingAddress", widget: "string"},
              {label: "Phone number", name: "phoneNumber", widget: "string"},
              {label: "Email", name: "email", widget: "string"},
              {label: "Mail address", name: "mailAddress", widget: "string"},
            ]}
